name: step-perf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - ld_impl_linux-64=2.43
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - networkx=3.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.12.11
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - maturin==1.8.6
      - mpmath==1.3.0
      - numpy==2.2.6
      - protobuf==6.31.1
      - pygraphviz==1.14
      - step-perf==0.1.0
      - sympy==1.13.3
      - torch==2.7.1+cpu
      - typing-extensions==4.12.2