name: step-perf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.50.1=hee588c1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - maturin==1.8.6
      - mpmath==1.3.0
      - numpy==2.2.6
      - protobuf==6.31.1
      - pygraphviz==1.14
      - step-perf==0.1.0
      - sympy==1.13.3
      - torch==2.7.1+cpu
      - typing-extensions==4.12.2